sudo: required
language: go
go:
  - 1.7
before_install:
  - wget https://github.com/yandex/tomita-parser/releases/download/v1.0/libmystem_c_binding.so.linux_x64.zip
  - unzip libmystem_c_binding.so.linux_x64.zip
  - sudo cp libmystem_c_binding.so /usr/lib/
  - sudo cp libmystem_c_binding.so /usr/lib/libmystem_c_binding.so.1
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
